### ISSUE TITLE
flask install error

### ISSUE THREAD

**Issue by iuiu34** [cdg720/cloud_run_sidecar#1]
hi,
thanks a lot for your post. More clear than the google official docs.

**bug**
In the docker build, the flask install raises an error.
Moving to
```
FROM python:3.9-slim
RUN pip install --upgrade pip

RUN pip install flask
````
Fix it for me and now your code works in my gcloud. 

**question**
- langchain dependency can be deleted, right?
-  would make sense to add `gcloud run services replace service.yaml` in the `build.sh`?

**pr**
Happy to do a PR for all this, if you ask me to

**Comment by cdg720** [comment]
1. yes. langchain is not needed. i was using langchain and noticed the problem
2. it is up to you

re: pr. this was meant to be a self-contained example to communicate with gcp support. i won't be maintaining or updating this repo. no need for a pr

**Comment by iuiu34** [comment]
uh, a quick responses, you're definetly not from google support.

Okey, understood. Thanks again for your repo, very useful.
